web:
  build: nginx
  links:
    - nodejs_db:nodejs_db
    - nodejs_tchat:nodejs_tchat
  volumes:
    - ./nginx/projet:/usr/share/nginx/html
  ports:
    - 80:80

nodejs_db:
  build: nodejs_db
  volumes:
    - ./nodejs_db/projet:/usr/src/app
  # links:
  #   - db:db

nodejs_tchat:
  build: nodejs_tchat
  volumes:
    - ./nodejs_tchat/projet:/usr/src/app
  ports:
    - 3000:3000
  # links:
  #   - db:db

db:
  build: mysql
  ports:
        - 3306:3306
